[package]
name = "pieter"
version = "0.1.0"
authors = ["Stephen Swatman <stephenswat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.4"
